kind: ReplicationController
apiVersion: v1
metadata:
  name: locust-worker
  namespace: pressure
  labels:
    name: locust
    role: worker
spec:
  replicas: 5
  selector:
    name: locust
    role: worker
  template:
    metadata:
      labels:
        name: locust
        role: worker
    spec:
      containers:
        - name: locust
          image: tstapler/locust-tasks:latest
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER
              value: locust-master
            - name: TARGET_HOST
              value: http://device-monitor-web:8898
